[Rendering]
RenderDistance = 24
SimulationDistance = 16
SmoothLighting = true
Shadows = true
UVs = true
ChunkSize = 16
WorldHeight = 256
WorldSeed = 42

[Textures]
AtlasSize = 1024

[Blocks]
Air = 0
Stone = 1
Grass = 2
Dirt = 3
Cobblestone = 4
Water = 7
Sand = 8

[Physics]
BaseMovementSpeed = 150.0
SprintMultiplier = 1.9
JumpForce = 9.5
Gravity = 25.0
Drag = 10.0
AutoJump = true

[Window]
Width = 1280
Height = 720
Title = "VulkanMC Engine"
Fullscreen = false
Maximized = true

[Controls]
Forward = 87
Backward = 83
Left = 65
Right = 68
Jump = 32
Sprint = 340
Escape = 256
QuickExit = 261

[Hardware]
PreferredGpuName = "AMD Radeon RX 6500 (RADV NAVI24)"

[Gameplay]
GameMode = "Survival" #Survival, Creative, Spectator
Entities = false
Trees = true
Clouds = true
Water = true
Lava = true
