name: Feature Request
description: Suggest an improvement or a new feature
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please describe the feature or improvement you want.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize your request in one sentence.
      placeholder: "Add multiplayer mode..."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the feature or improvement in detail.
      placeholder: "Multiplayer mode would allow..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
      placeholder: "To play with friends..."
    validations:
      required: false
